### ISSUE TITLE
Misssing diagram mode view for the service.xml file

### ISSUE THREAD

**Issue by sytolk** [liferay/liferay-intellij-plugin#101]
The same like Liferay Service Builder service.xml in Liferay Dev Studio CE:
https://dev.liferay.com/en/develop/tutorials/-/knowledge_base/7-1/defining-relationships-between-service-entities

**Comment by jtydhr88** [comment]
hey @sytolk there is no any diagram editors for xml files right now, I opened one ticket for that: https://issues.liferay.com/browse/INTELLIJ-56 but I could not ensure when we will implement it.
