### ISSUE TITLE
service.xml inspections

### ISSUE THREAD

**Issue by dmarks2** [liferay/liferay-intellij-plugin#105]
I have seen some requests to make some improvements for the service.xml (a graphical wizard or a diagram editor). I've tried to reuse the "ER Diagram" functionality of IntelliJ to create a diagram from a service.xml. It is far from being ready, it's read-only for now, does not show relationships correctly etc.

As a first step to improve things in the service.xml, I would like to add some "inspections" for the file. By using inspections IntelliJ will show some common mistakes in the service.xml and offers a quick fix (if possible). Inspections can be configured by the developer, so they can be turned off if a developer does not want to use them.

I would like to add the following inspections:

- Check for a valid `<namespace>` tag (no quickfix)
- Check that `<exception>` entries do not have "Exception" at the end of the name (quickfix: Remove "Exception")
- Check for duplicate `<exception>` entries (quickfix: remove duplicate)
- Check for duplicate `<column>` entries (quickfix: remove duplicate)
- Check for duplicate `<finder>` entries (quickfix: remove duplicate)
- Check for duplicate `<entity>` entries (quickfix: remove duplicate)
- Check that the primary key columns have the type "int", "long" or "string" (no quickfix)
- Ensure that entities having a uuid also have a primary key column (no quickfix)

@jtydhr88 can you create a JIRA issue for this?

**Comment by jtydhr88** [comment]
hey @dmarks2 can you post some screenshots of ER Diagram or any examples? I'd like to talk @gamerson about that. thanks.

**Comment by dmarks2** [comment]
hey @jtydhr88,

here is a small screencast of the ER diagram. As already said, it is far from being complete...

![diagram](https://user-images.githubusercontent.com/10325752/56369626-04b1f300-61fa-11e9-9408-9530153e60ac.gif)

**Comment by dmarks2** [comment]
Hey @jtydhr88, can you create a JIRA issue for the "service.xml inspections" part? 

> As a first step to improve things in the service.xml, I would like to add some "inspections" for the file. By using inspections IntelliJ will show some common mistakes in the service.xml and offers a quick fix > (if possible). Inspections can be configured by the developer, so they can be turned off if a developer does not want to use them.
>
>I would like to add the following inspections:
>
>Check for a valid <namespace> tag (no quickfix)
>Check that <exception> entries do not have "Exception" at the end of the name (quickfix: Remove >"Exception")
>Check for duplicate <exception> entries (quickfix: remove duplicate)
>Check for duplicate <column> entries (quickfix: remove duplicate)
>Check for duplicate <finder> entries (quickfix: remove duplicate)
>Check for duplicate <entity> entries (quickfix: remove duplicate)
>Check that the primary key columns have the type "int", "long" or "string" (no quickfix)
>Ensure that entities having a uuid also have a primary key column (no quickfix)

**Comment by jtydhr88** [comment]
The changes are merged, @gamerson can you close this issue?
Thanks a lot! @dmarks2
