### ISSUE TITLE
JSP inspections

### ISSUE THREAD

**Issue by dmarks2** [liferay/liferay-intellij-plugin#107]
Similar to the service.xml inspections I would like to add some inspections for JSPs. Those should highlight common mistakes in JSPs. 

The inspections I would like to add are:
* Check for double quotes inside taglib attributes
* String concatenation inside taglib attributes

The inspections will look like this:

Check for double quotes:
![jsp_inspections](https://user-images.githubusercontent.com/10325752/58095438-4ce67b80-7bd3-11e9-9c62-bd915c34edc3.gif)

String concatenation:
![jsp_inspections_2](https://user-images.githubusercontent.com/10325752/58095454-5243c600-7bd3-11e9-86f8-94eb7e01c10b.gif)

@jtydhr88 can you create a JIRA issue for this?

**Comment by jtydhr88** [comment]
open here https://issues.liferay.com/browse/INTELLIJ-70

**Comment by jtydhr88** [comment]
hey @gamerson can you close this as we already merged it. thanks @dmarks2 a lot!
