### ISSUE TITLE
Update XML Schemas and Portlet 3.0 Spec

### ISSUE THREAD

**Issue by dmarks2** [liferay/liferay-intellij-plugin#110]
I would like to add XML Schema files for Liferay 7.2. and the Portlet 3.0 Specification. Additionally I would like to add the OSGi properties for the Portlet.class which are new from the Portlet 3.0 Specification.

@jtydhr88 can you create a Jira Issue?

**Comment by jtydhr88** [comment]
open here https://issues.liferay.com/browse/INTELLIJ-78

**Comment by dmarks2** [comment]
Pull request sent https://github.com/jtydhr88/liferay-intellij-plugin/pull/82
