### ISSUE TITLE
Update taglib code completions for Liferay 7.1/7.2

### ISSUE THREAD

**Issue by dmarks2** [liferay/liferay-intellij-plugin#112]
Several taglibs have been added in Liferay 7.1/7.2 (e.g. liferay-asset, liferay-comment, liferay-export-import-changeset) and other taglibs got new tags and attributes.

I would like to update the code completion features (language keys, css classes, Javascript, Java classnames) to support those new taglibs/tags/attributes. 

@jtydhr88 can you create a JIRA ticket?

**Comment by jtydhr88** [comment]
opened here https://issues.liferay.com/browse/INTELLIJ-82
btw, we are starting to add LSP support for the three tools(eclipse, intelliJ, VS Code), and now it is under calculating requestments. Firstly, I will finish properties files support up, and then xml, in the future, I think the JSP/taglib support will be moved to LSP as well.

**Comment by jtydhr88** [comment]
I will post the requirements/schedule in BLADE repo later.
