### ISSUE TITLE
Run configuration for WildFly 16

### ISSUE THREAD

**Issue by BaranovNikita** [liferay/liferay-intellij-plugin#115]
Hello! If i try create run configuration for Liferay 7.2 with WildFly 16 - i cant, because "Bundle type" field is empty after select server folder. But it work with WildFly 11

**WildFly 16:**
![image](https://user-images.githubusercontent.com/9808191/73490180-02054080-43bd-11ea-81d8-b9d6ad67806d.png)

**WildFly 11:**
![image](https://user-images.githubusercontent.com/9808191/73490202-0e899900-43bd-11ea-8636-4858229ea9c4.png)

**Comment by yanan** [comment]
Thanks for catching this, please watch https://issues.liferay.com/browse/INTELLIJ-99.

**Comment by BaranovNikita** [comment]
> Thanks for catching this, please watch https://issues.liferay.com/browse/INTELLIJ-99.

Yep. Now i can select wildfly > 10. But has error:
java.lang.NoClassDefFoundError: org/wildfly/common/net/HostName

![image](https://user-images.githubusercontent.com/9808191/74747686-6149c880-5278-11ea-88a6-10520bffa7f0.png)

**Comment by simonjhy** [comment]
we have fixed this. Here is jira link: https://issues.liferay.com/browse/INTELLIJ-99
