### ISSUE TITLE
Relative paths are not resolved properly in XML files

### ISSUE THREAD

**Issue by dmarks2** [liferay/liferay-intellij-plugin#121]
I've found a small issue that I would like to fix.

In the Liferay IntelliJ plugin there is a functionality which resolves files inside XML files. For example when you create a `default.xml` to define the available permission actions you can include other files here.

The current implementation does not properly resolve relative paths in those files. Code completion does not work and resolving the reference (Ctrl + Click) does not work.

Consider the following example:

Given a directory structure:

src/
src/main/
src/main/resources
src/main/resources/META-INF
src/main/resources/META-INF/resource-actions
src/main/resources/META-INF/resource-actions/default.xml
src/main/resources/META-INF/resource-actions/custom.xml

The `default.xml` looks like this:

![image](https://user-images.githubusercontent.com/10325752/76420641-b920ae80-63a2-11ea-8074-f99de7eccc2c.png)

Ctrl-Click on the `custom.xml` should open the file at that location, but it just shows an error message "Cannot find declaration to go". The same applies if you place the cursor e.g. behind `META-INF/resource-actions/` and press Ctrl+Space. It should list up all files present in that directory but it just shows "no suggestions"

@gamerson can you create a JIRA ticket for this? I would like to contribute a fix...

**Comment by simonjhy** [comment]
Hi @dmarks2, I will create jira ticket. Thanks dominik

**Comment by simonjhy** [comment]
its the jira link: https://issues.liferay.com/browse/INTELLIJ-110

**Comment by dmarks2** [comment]
Hi @simonjhy,

thanks for creating the ticket. Here is the pull request: https://github.com/simonjhy/liferay-intellij-plugin/pull/21
