### ISSUE TITLE
Disables gradle for non liferay projects

### ISSUE THREAD

**Issue by ingensky** [liferay/liferay-intellij-plugin#124]
Plugin version 1.7.3
Idea version 2020.1.1
When plugin is enabled, gradle of non related to liferay projects does not work properly.
Dependencies are downloaded, but there is no visibility for them in project.
External Libraries contains only Java JDK
All imports are red and unavailable.
Reproduces on any non liferay gradle (gradle-wrapper, tryied several different versions) project

Reproduces on Ubuntu 18.04 and Windows 10
Steps:

- Create simple gradle project
- Add dependency (for JUnit for example)
- Junit jar appears in External Libraries
- Enable Liferay plugin
- Restart ide and reimport gradle
- External Libraries - JUnit is missing there

**Comment by simonjhy** [comment]
Hi ingensky, thanks for finding the bug(https://issues.liferay.com/browse/INTELLIJ-124). we found this issue and fixed it. We will publish a new vesion plugin soon.

**Comment by gamerson** [comment]
Thanks for the repo @ingensky   I will close this, since we have already fix this and will be available in next plugin version.

**Comment by ingensky** [comment]
Thanks a lot guys! That was fast)
