### ISSUE TITLE
NPE happened for non-liferay project

### ISSUE THREAD

**Issue by jtydhr88** [liferay/liferay-intellij-plugin#131]
When working in a non-liferay-workspace project in IntelliJ IDEA installed with Liferay plugin, it will throw NullPointerException:
![image](https://user-images.githubusercontent.com/860985/104793477-bde19a80-57dd-11eb-8b24-c28c2c4b4a20.png)
Steps to reproduce:
1. create a maven project.
2. write some codes.
3. see the right-bottom icon

**Comment by lily94299570** [comment]
Hi @jtydhr88 ,
This problem has been fixed in the latest release 1.9.0, you can install 1.9.0 with intellij 2020.3 and try again. If you have any problems, please contact us again, thanks.

**Comment by yanan** [comment]
Closing this and please free feel to reopen/create a new one if there is anything, thanks.
