### ISSUE TITLE
OSGi component property code completion does not work for single properties

### ISSUE THREAD

**Issue by dmarks2** [liferay/liferay-intellij-plugin#132]
OSGi component properties can be written with an array initializier or with a single value.

Code completion for those properties only works when "property" is an array, e.g.:

![image](https://user-images.githubusercontent.com/10325752/112149206-056e1380-8bdf-11eb-8626-d6f3d3f05552.png)

However if property is just a single value, code completion does not work and suggests some arbirtrary values:

![image](https://user-images.githubusercontent.com/10325752/112149349-2b93b380-8bdf-11eb-99c2-5218e064a16a.png)

**Comment by dmarks2** [comment]
created a JIRA issue here: https://issues.liferay.com/browse/INTELLIJ-184

**Comment by gamerson** [comment]
Fixed here: https://github.com/liferay/liferay-intellij-plugin/commit/d626124339c5fa4db26e745f59dde24aa6bf0824
