### ISSUE TITLE
The constructors of the classes which implement ServiceWrapper should not be marked as grey(unused)

### ISSUE THREAD

**Issue by jtydhr88** [liferay/liferay-intellij-plugin#203]
For the OSGi components which implement ServiceWrapper, the classes will be used in portal layer, not from local side, so the constructors should be normal, rather than being marked as unused.
![image](https://user-images.githubusercontent.com/860985/164461078-159f9271-3827-465f-b598-cf8970723942.png)

**Comment by dmarks2** [comment]
Yes @jtydhr88 , those ServiceWrappers are called by OSGi, so they are "implicitly" used.

I think this would be true for every class annotated with @Component, right? Did not see many components having an explicit constructor, but if there is one I think it will be called by OSGi anyway. 

So "every" constructor in a @Component should not be marked as unused. What do you think?

**Comment by jtydhr88** [comment]
@dmarks2 I agree with you, the class with @component means it will be called by OSGi, and should be marked as normal.

**Comment by dmarks2** [comment]
@jtydhr88, @simonjhy I've created a ticket for this feature: https://issues.liferay.com/browse/INTELLIJ-236

Think it should be easy to implement, I will have a look at it...

**Comment by jtydhr88** [comment]
thanks @dmarks2!

**Comment by dmarks2** [comment]
Feature is implemented in Version 2.0.2. Issue could be closed @jtydhr88 .

**Comment by jtydhr88** [comment]
Thanks to let me know!
