### ISSUE TITLE
Target Platform Indexing not working when Workspace is on WSL2 distribution

### ISSUE THREAD

**Issue by anthonybaudouin** [liferay/liferay-intellij-plugin#217]
Hello,

I'm working on Windows 10 + WSL2 (Ubuntu 20.04.4 LTS).
My Liferay Workspace is located in the WSL2 distribution and I observe an issue with the Liferay Target platform indexing feature: only gradle dependencies explicitely declared in the workpace's build.gradle files are visible in IntelliJ "External Libraries" section whereas we should expect that all dependencies included in Liferay BOM files be visible as well.
However, in my gradle.properties the following property is defined with the right value:
` target.platform.index.sources=true`

Here is my setup:

- Windows 10 (build 19042.1706)
- WSL2 distribution: Ubuntu 20.04.4 LTS
- IntelliJ IDEA Ultimate Edition 2022.1.3
- Liferay IntelliJ plugin 2.0.1

**Comment by simonjhy** [comment]
@anthonybaudouin thanks for using our plugin, we will firstly check it in local.

**Comment by simonjhy** [comment]
what's product or target platform version you used ? I tested the latest dxp-7.4-u31 and it can download the target plaform and  are visible in IntelliJ "External Libraries" section

**Comment by anthonybaudouin** [comment]
@simonjhy, whatever the Liferay version I used (dxp-7.4-u31), none Liferay dependencies are visible in "External libraries" section.
The attached screenshot shows this behavior.

![target_platform_issue_under_wsl2](https://user-images.githubusercontent.com/58040755/177716091-267400f9-6fdb-49c0-8a60-9873c314deb0.png)

**Comment by simonjhy** [comment]
@anthonybaudouin  we reprodcue this issue. Its an issue that java io file can not return correcty absolute file path when the module project stored in wsl environment. Here the jira ticket https://issues.liferay.com/browse/INTELLIJ-246

**Comment by anthonybaudouin** [comment]
Great news @simonjhy. Hoping a fix will be provided soon :)
