### ISSUE TITLE
Activator module creation is not available

### ISSUE THREAD

**Issue by gitti20M** [liferay/liferay-intellij-plugin#274]
I can not found the project type activator in the list:

![image](https://github.com/liferay/liferay-intellij-plugin/assets/61048251/311dc434-8278-4f91-a603-9ccaf05a43f1)

On the liferay tutorial site it is there:

![image](https://github.com/liferay/liferay-intellij-plugin/assets/61048251/ce22de88-2d6a-488e-84f4-8661528f4034)

I use the plugin version 2.0.5

**Comment by simonjhy** [comment]
@gitti20M the activator did not support any more. The liferay tutorial site maybe outdate, we will notify document team to update
