### ISSUE TITLE
Product Version

### ISSUE THREAD

**Issue by PensieroLaterale** [liferay/liferay-intellij-plugin#284]
On wizard the field "Product Version" is empty. Do I need some configuration for Liferay plugin in order to have the list of Liferay versions?
<img width="808" alt="Screenshot 2023-09-06 alle 15 33 35" src="https://github.com/liferay/liferay-intellij-plugin/assets/74310560/1aa24494-0244-49fe-b565-f81cc3e60d56">

**Comment by simonjhy** [comment]
I used Idea Ultimate 2023.2.1 + liferay plgin 2.0.5 and I did not get this error. It could correctly show product version. Can you help to use blade command in command line to test with "blade init -l" to confirm whether blade can get product verison?

**Comment by LouisDeGuinness** [comment]
> blade init -l
dxp-7.4-u93
dxp-7.4-u10
dxp-7.3-u31
dxp-7.2-sp8
dxp-7.1-sp8
dxp-7.1-fp27
dxp-7.0-sp17
portal-7.4-ga92
portal-7.4-ga61
portal-7.3-ga8
portal-7.2-ga2
portal-7.1-ga4
portal-7.0-ga7
commerce-2.0.7-7.2
commerce-2.0.7-7.1
Updates available to the installed version: 4.1.2.202212260534
-> (Snapshot) Optional[5.0.1.202308300348]       Run `blade update` to install
-> (Release) Optional[5.0.0]                     Run `blade update -r` to install

**Comment by PensieroLaterale** [comment]
I'm using macbook Pro apple silicon M2 Max with macOS Ventura 13.5.1
blade is ok I have:
dxp-7.4-u93
dxp-7.4-u10
dxp-7.3-u31
dxp-7.2-sp8
dxp-7.1-sp8
dxp-7.1-fp27
dxp-7.0-sp17
portal-7.4-ga92
portal-7.4-ga61
portal-7.3-ga8
portal-7.2-ga2
portal-7.1-ga4
portal-7.0-ga7
commerce-2.0.7-7.2
commerce-2.0.7-7.1


but the problem when I try to create new project where "Product Version" field remains empty....

IntelliJ IDEA 2023.2.1 (Ultimate Edition)
Build #IU-232.9559.62, built on August 23, 202
Liferay Plugin 2.0.5

**Comment by simonjhy** [comment]
we release new version plugin. Can you try to check it again?

**Comment by LouisDeGuinness** [comment]
My check was successful, everything's fine. Thanks!
