### ISSUE TITLE
Product Version shows unexpected value

### ISSUE THREAD

**Issue by palimer6** [liferay/liferay-intellij-plugin#293]
I've been having a similar issue to #284 before updating to 2.0.6
After updating, the field now gets initialized with only the value `org/apache/commons/codec/binary/Base64`
This does not change when checking the Show All Product Versions box.

IntelliJ Version: 2023.2.3

**Comment by simonjhy** [comment]
1)Can you upload a reproduce video? 
2)Can you try to delete the blade-latest.jar from this folder {your home dir}/.liferay-intellij-plugin/

**Comment by palimer6** [comment]
I cannot provide a recording at this time, sorry.
The steps I take before the issue are:

1. File > New > Project...
2. Liferay GradleWorkspace > Next

After this, the Product version field is empty for 2 seconds and then shows `org/apache/commons/codec/binary/Base64`

If I delete `blade-latest.jar`, the same thing happens and the file is recreated.

**Comment by simonjhy** [comment]
what file was created? Can you provide it?
