### ISSUE TITLE
Need connect gogoshell in manual after start liferay runtime

### ISSUE THREAD

**Issue by haoyisun** [liferay/liferay-intellij-plugin#45]
1.start a liferay runtime  
2.open gogoshell client at intellij, need open localhost 11311 in manual

Environment:  win10  jre1.8

**Comment by jtydhr88** [comment]
what is this for? the Gogo shell view should not be related to watch task.

**Comment by haoyisun** [comment]
sorry, I get wrong, and re-edit my comment @jtydhr88
