### ISSUE TITLE
Avoid showing "never assigned" warning for fields annotated by Reference or Inject

### ISSUE THREAD

**Issue by dantewang** [liferay/liferay-intellij-plugin#61]
IntelliJ IDEA by default checks whether a field in a class is assigned; if not, it highlights the field with waved underline and a warning "field _fieldName is never assigned".

In Liferay, a developer can use `Reference` annotation on a field so that the field is assigned by the OSGi framework:

![reference-annotation](https://user-images.githubusercontent.com/1185063/43629181-2b1f7d14-972f-11e8-90bb-f2eb02b11f40.png)

When writing Arquillian tests, one can also use `Inject` annotation in a test class:

![inject-annotation](https://user-images.githubusercontent.com/1185063/43629188-2fbce3b6-972f-11e8-99fd-4f34f3084913.png)

For these occasions, liferay-intellij-plugin should prevent the warning from the annotated fields.

**Comment by dmarks2** [comment]
Should be rather easy to implment. IntelliJ does the same e.g. for Spring annoations like @Autowired. It can be done using an "ImplicitUsageProvider" in the plugin.

I will have a look at it and implement such an ImplicitUsageProvider.
