### ISSUE TITLE
Code Completion, Syntax highlighting etc. for Javascript in Liferay Taglibs

### ISSUE THREAD

**Issue by dmarks2** [liferay/liferay-intellij-plugin#62]
Several attributes of Liferay tags support the use of Javascript. E.g. `<aui:a onClick="" />` or inside the tag itself like `<aui:script>` or `<aui:validator>`. 

I would like to add a functionality to allow syntax highlighting, code completion, syntax checking etc. for those attributes and tags. 

Example before:
![image](https://user-images.githubusercontent.com/10325752/43776601-a4b965bc-9a50-11e8-86af-07a042fbabec.png)

After:
![image](https://user-images.githubusercontent.com/10325752/43776611-aaf1bf10-9a50-11e8-98f9-0f22c3a75d95.png)

**Comment by jtydhr88** [comment]
hey @dmarks2, as talking with @gamerson, add the frontend as the gradle dependency is not the correct way for Developers, but we could add the some thing like **Web** support we already done.
I opened the issue #76 for it and we may work on it in next version
