### ISSUE TITLE
Code assistance for Liferay taglibs in FreeMarker templates

### ISSUE THREAD

**Issue by garyttierney** [liferay/liferay-intellij-plugin#65]
This is a feature that will only work on IntelliJ Ultimate (requires JavaEE support).

The plugin maintained by @dmarks2 has support for parsing JSTL desriptors and feeding the result into the `FtlGlobalVariableProvider` [extension](https://github.com/dmarks2/liferay-plugin-intellij/blob/master/src/main/java/de/dm/intellij/liferay/language/freemarker/LiferayFtlVariableProvider.java).

**Comment by jtydhr88** [comment]
Move to JIRA ticket https://issues.liferay.com/browse/INTELLIJ-9
