### ISSUE TITLE
disable to index the bundles folder in Liferay workspace project

### ISSUE THREAD

**Issue by jtydhr88** [liferay/liferay-intellij-plugin#66]
after run initBundle, there will be bundle folder (tomcat) inside the Liferay workspace project. Intellij Ultimate will auto-detect this folder.
![1](https://user-images.githubusercontent.com/860985/44215741-d7fa9700-a1a5-11e8-889d-a85a1541411e.png)
![2](https://user-images.githubusercontent.com/860985/44215651-9b2ea000-a1a5-11e8-9a46-ee97a3f06cb7.png)
should to disable to index this folder.

**Comment by dmarks2** [comment]
Hey @jtydhr88,
that could probably be done by marking the bundle directory as an excluded folder. As far as I know excluded folders are not examined or indexed by IntelliJ.

I my own plugin I do the same for "build" and "dist" directories which are created by npm/gulp when you compile a theme or layout template. 

See an example here: https://github.com/dmarks2/liferay-plugin-intellij/blob/e80983753ed4f2cdbda5368f5a704f9098b14b0f/src/main/java/de/dm/intellij/liferay/theme/LiferayPackageJSONParser.java#L95

**Comment by jtydhr88** [comment]
thanks a lot @dmarks2, I will take a look at it later

**Comment by jtydhr88** [comment]
Moved to JIRA project: https://issues.liferay.com/browse/INTELLIJ-3
