### ISSUE TITLE
Feature: Make the list of "injecting" annotations configurable

### ISSUE THREAD

**Issue by dantewang** [liferay/liferay-intellij-plugin#77]
This is related to https://github.com/liferay/liferay-intellij-plugin/issues/61

In #61, the `@Inject` annotation in the screenshot was actually `com.liferay.portal.test.rule.Inject`.

Additionally, `@Inject` could also mean `javax.inject.Inject`, which is used by Portlet Spec 3.0 "Bean Portlet".

It will be great to make this list configurable; or at least add the two above to the list.

**Comment by dmarks2** [comment]
@dantewang I would prefer to just add those two annotations to the plugin. To make it configurable we would need an user interface (or similar). And I think the "normal" developer would not like to configure those annotations manually.

**Comment by dantewang** [comment]
@dmarks2 Thanks! I'm definitely OK with that.

**Comment by dmarks2** [comment]
@jtydhr88 sent as https://github.com/jtydhr88/liferay-intellij-plugin/pull/27

**Comment by dantewang** [comment]
Thanks @dmarks2 !
