### ISSUE TITLE
Additional JSP Taglibs attributes for language keys and css attributes

### ISSUE THREAD

**Issue by dmarks2** [liferay/liferay-intellij-plugin#83]
There are some more taglibs which support langage keys and css attributes. I would like to add support for the following taglibs:

- liferay-ddm
- liferay-site
- liferay-staging
- liferay-editor
- liferay-adaptive-media
- clay

@jtydhr88 Could you please create a JIRA issue for this?

**Comment by jtydhr88** [comment]
open here: https://issues.liferay.com/browse/INTELLIJ-24
