### ISSUE TITLE
Classname and Java Bean properties code completion for JSP taglibs

### ISSUE THREAD

**Issue by dmarks2** [liferay/liferay-intellij-plugin#85]
For some JSP tags you can provide a Java classname or refer to a Java Bean property. I would like to add code completion for those tags, e.g. adding a classname for `<aui:model-context model='classname'>` or refering to a bean property for `<aui:input name='property'>`. 

![jsp_classname](https://user-images.githubusercontent.com/10325752/49365733-d10d7b00-f6e7-11e8-8d41-d7035fd76490.gif)

@jtydhr88 could you create a JIRA issue for this?

**Comment by jtydhr88** [comment]
open here https://issues.liferay.com/browse/INTELLIJ-27
