### ISSUE TITLE
OSGi component properties code completion does not work when using multiple service classes

### ISSUE THREAD

**Issue by dmarks2** [liferay/liferay-intellij-plugin#89]
The code completion for OSGi component properties does not work when you are using multiple service classes. For example if you are using

`@Component(
    property = { "..." },
    service = {AddPortletProvider.class, ViewPortletProvider.class}
)
`

code completion does not work, i.e. it does not offer any properties.

@jtydhr88 I would like to fix that. Can you create a JIRA issue?

**Comment by jtydhr88** [comment]
Could you close it as it already is fixed, thanks!
