### ISSUE TITLE
Performance warning for LiferayServiceXMLLineMarkerProvider

### ISSUE THREAD

**Issue by dmarks2** [liferay/liferay-intellij-plugin#91]
In the log file a performance warning appears for the LiferayServiceXMLLineMarkerProvider. The following message appears in the log file:

`WARN - eInsight.daemon.LineMarkerInfo - Performance warning: LineMarker is supposed to be registered for leaf elements only, but got: XmlTag:entity (class com.intellij.psi.impl.source.xml.XmlTagImpl) instead. First child: XmlToken:XML_START_TAG_START (class com.intellij.psi.impl.source.xml.XmlTokenImpl)
Please see LineMarkerProvider#getLineMarkerInfo(PsiElement) javadoc for detailed explanations. 
`

@jtydhr88 I would like to fix that. Can you create a JIRA issue?

**Comment by jtydhr88** [comment]
hey @dmarks2, opened here https://issues.liferay.com/projects/INTELLIJ/issues/INTELLIJ-40
