### ISSUE TITLE
Launching Liferay in Tomcat with OpenJdk 11.0.2

### ISSUE THREAD

**Issue by joaorebelo-ar** [liferay/liferay-intellij-plugin#92]
Hello team,

First of all, thank you very much for this plugin.

I have been trying to get Liferay 7.1 GA3 to run in Intellij IDEA Community 2018.3 using OpenJdk 11.0.2.

I keep running into the following error when starting the server while following your instructions:

> Error: Could not create the Java Virtual Machine.
> -Djava.endorsed.dirs=D:\personal\tools\liferay-ce-portal-7.1.1-ga2\tomcat-9.0.10\endorsed is not supported. Endorsed standards and standalone APIs
> Error: A fatal exception has occurred. Program will exit.
> in modular form will be supported via the concept of upgradeable modules.

I have removed all references of the property `java.endorsed.dirs` from Tomcat's configuration files namely **catalina.bat**. Liferay starts if launched manually from the command prompt, but not if I try to launch it from the plugin.

Taking a brief look at your code I might have caught the issue in the following method bellow in `com.liferay.ide.idea.server.portal.PortalTomcatBundle.java` which always set the above mentioned property.

```
private String[] _getRuntimeVMArgs() {
		List<String> args = new ArrayList<>();
		Path tempPath = FileUtil.pathAppend(bundlePath, "temp");
		Path endorsedPath = FileUtil.pathAppend(bundlePath, "endorsed");

		args.add("-Dcatalina.base=" + bundlePath);
		args.add("-Dcatalina.home=" + bundlePath);
		args.add("-Dfile.encoding=UTF8");
		args.add("-Djava.endorsed.dirs=" + endorsedPath);
		args.add("-Djava.io.tmpdir=" + tempPath);
		args.add("-Djava.net.preferIPv4Stack=true");
		args.add("-Djava.util.logging.config.file=" + FileUtil.pathAppend(bundlePath, "conf/logging.properties"));
		args.add("-Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager");
		args.add("-Dorg.apache.catalina.loader.WebappClassLoader.ENABLE_CLEAR_REFERENCES=false");
		args.add("-Duser.timezone=GMT");

		return args.toArray(new String[0]);
	}
```

Could you please have a look?
I am available to provide any further info if necessary.

Thank you.

**Comment by jtydhr88** [comment]
hey, thanks for reporting this issue, we will take a look today.

**Comment by jtydhr88** [comment]
opened the jira issue here https://issues.liferay.com/projects/INTELLIJ/issues/INTELLIJ-41 and we will fix it in next release, thanks again for reporting.

**Comment by simonjhy** [comment]
Hey, I remove the endorsed and try to start portal with command line. I found some exception with liferay portal and I confirmed this issue with portal team that the portal master branch can  start with JDK11. The published version maybe not.  We will remove this endorsed in next release version. Thanks

**Comment by joaorebelo-ar** [comment]
Yes. Through the command line I am able to start the server. It throws some exceptions, but the portal seems to run just fine. I did have a look at the modules loaded in the gogo shell and they seemed ok. The exceptions are annoying though. :)

**Comment by jtydhr88** [comment]
hey @joaorebelo-ar, the issue will be fixed in #91 and I have no idea about the exact day of next release as we released the latest one a few days ago, if you need this fix then you may need to build manually, let me know if you have any questions about this.

**Comment by joaorebelo-ar** [comment]
@jtydhr88 I have seen the commit. Tackling the issue as fast as you did guys. Kudos!

**Comment by jtydhr88** [comment]
hey @joaorebelo-ar we already released the latest one with this fix, but it still is pending the Jetbrains approval, it will take 2 or 3 days normally.
So can you close this issue?
