### ISSUE TITLE
Feature: support for Liferay 6.x

### ISSUE THREAD

**Issue by simon387** [liferay/liferay-intellij-plugin#94]
Why there is no support for Liferay 6.x projects?

**Comment by dmarks2** [comment]
Hey @simon387,
most of the functionality of the plugin is focused on Liferay 7.x. But some features should still work on Liferay 6.x projects, as the functionality behind did not change between Liferay 6.x and Liferay 7.x. 

Features which should still work for Liferay 6.x projects (untested):
- Service Line Markers (jump from service.xml to the implementation and back)
- code completion inside custom-sql/default.xml and portlet-model-hints.xml
- code completion for file references inside different Liferay XML files 
- code completion for JSP taglibs (css, resource bundles, java beans etc).

So the IntelliJ plugin is not completely useless for Liferay 6.x :-)

**Comment by simon387** [comment]
thank you for the answers, so I have to use the lifeay IDE (eclipse based) and the liferay-plugin-sdk to create a new project and plugins : (
