### ISSUE TITLE
Liferay IntelliJ Plugin marks syntax errors on bnd.bnd files

### ISSUE THREAD

**Issue by dantewang** [liferay/liferay-intellij-plugin#99]
Liferay IntelliJ Plugin provides syntax highlight or analysis for bnd.bnd, however it marks various usages/formats used by liferay-portal as errors.

1. It doesn't recognize line wrapping represented by `\`
2. It can't correctly parse complicated syntax such as those inside `Provide-Capability`

For example, in https://github.com/liferay/liferay-portal/blob/master/modules/apps/staging/staging-bar-web/bnd.bnd,

![intellij-plugin-bnd](https://user-images.githubusercontent.com/1185063/53713573-44a95a80-3e86-11e9-9cbf-8a6d254ca580.png)

1. It expects a whitespace after the `:` in the line `Provide-Capability:\`, however the `\` means "soft wrap" of the same line;
2. It expects a whitespace after the `:` in the `resource.bundle.aggregate:String` but there shouldn't be a whitespace in this case; also, it's rendering wrong syntax highlight;
3. It also expects `;` at the end of line 5 & 7

Similar errors are also shown in bnd.bnd of other `Provide-Capability` bundles:

![intellij-plugin-bnd-2](https://user-images.githubusercontent.com/1185063/53714005-d36aa700-3e87-11e9-8715-a2c5edf20e24.png)

Such syntax may also be used by other Liferay developers utilizing `Provide-Capability`, etc. so it's not limited to Liferay's own modules.

**Comment by gamerson** [comment]
hey @jtydhr88  can we create an INTELLIJ jira ticket for this and fix up our parser?

**Comment by jtydhr88** [comment]
open here https://issues.liferay.com/browse/INTELLIJ-53
